export const queryKeys = {
  RANKING_LIST: 'allUserRankingList',
  RECENT_MATCH_LIST: 'recentMatchList',
  USER_REQUESTS: 'user-requests',
  USER_OWN_POSTS: 'user-posts',
  USER_HISTORY: 'user-history',
  POSTLIST: 'postList',
  GUESTLIST: 'guestList',
  JOINLIST: 'joinList',
  ACCEPTLIST: 'acceptList',
  REVIEWLIST: 'reviewList',
  MAPLIST: 'mapList',
  KEYWORD: 'keywordList',
  SEARCH: 'searchList',
  CHAT_ROOMS: 'chat-rooms',
  CHAT_HISTORY: 'chat-history',
};
